### ISSUE TITLE
3.0.0-next has broken the nice pre-render build error

### ISSUE THREAD

**Issue by lydell** [developit/preact-cli#662]
**Do you want to request a *feature* or report a *bug*?**
bug

**Steps to reproduce**
Repro repo: https://github.com/lydell/preact-cli-build-error

1. `npm ci`
2. `npm run dev`

The build should fail, because `src/index.js` intentionally has an error: It
unconditionally tries to access `window`.

preact-cli@2.2.1 output (good):

```
ReferenceError: window is not defined
method: JkW7
at: /home/lydell/stuff/preact-simple-test/src/index.js:3:12

Source code:

import { h } from 'preact';
console.log(window.location);
export default () => <p>Hello, world!</p>;

This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.
```

preact-cli@3.0.0-next.14 output (bad):

```
(node:16457) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Build [===============] 98% (1.4s) after emitting ssr-bundle.js ⏤  3.86 kB (+3.86 kB)

Build [===============] 98% (1.2s) after emitting ssr-build/ssr-bundle.js ⏤  0 B (-3.86 kB)
         bundle.048c7.js ⏤  3.98 kB (+3.98 kB)
      polyfills.e99bc.js ⏤  2 kB (+2 kB)
              index.html ⏤  415 B (+415 B)

Total precache size is about 77.7 kB for 5 resources.
✖ ERROR Template execution failed: TypeError: sourceMapConsumer.originalPositionFor is not a function
✖ ERROR   TypeError: sourceMapConsumer.originalPositionFor is not a function
  
  - prerender.js:54 handlePrerenderError
    [preact-simple-test]/[preact-cli]/lib/lib/webpack/prerender.js:54:32
  
  - prerender.js:36 module.exports
    [preact-simple-test]/[preact-cli]/lib/lib/webpack/prerender.js:36:3
  
  - render-html-plugin.js:44 Object.ssr
    [preact-simple-test]/[preact-cli]/lib/lib/webpack/render-html-plugin.js:44:31
  
  - template.html:129 L6k0.module.exports
    [preact-simple-test]/[preact-cli]/lib/resources/template.html:129:37
  
  - index.js:284 Promise.resolve.then
    [preact-simple-test]/[html-webpack-plugin]/index.js:284:18
  
  - es6-promise.js:409 tryCatch
    [preact-simple-test]/[es6-promise]/dist/es6-promise.js:409:12
  
  - es6-promise.js:424 invokeCallback
    [preact-simple-test]/[es6-promise]/dist/es6-promise.js:424:13
  
  - es6-promise.js:176 
    [preact-simple-test]/[es6-promise]/dist/es6-promise.js:176:14
  
  - es6-promise.js:128 flush
    [preact-simple-test]/[es6-promise]/dist/es6-promise.js:128:5
  
  - next_tick.js:61 process._tickCallback
    internal/process/next_tick.js:61:11
  

(node:16457) UnhandledPromiseRejectionWarning: Build failed! null
(node:16457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16457) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Please mention other relevant information.**
- Node version: 10.10.0
- npm version: 6.4.1
- Operating system: Ubuntu 18.04
- CLI version: 3.0.0-next.14
- Browser: n/a

**Comment by ForsakenHarmony** [comment]
Fixed

**Comment by ljmerza** [comment]
how was this fixed? i still get this error on the latest preact-cli so not sure what to do here

**Comment by rschristian** [comment]
@ljmerza Can you provide a reproduction? Looks like it was solved by correcting something in the stack trace generation.

**Comment by ljmerza** [comment]
```
⚠ WARN Could not find sw.js in /home/lmerza/projects/src. Using the default service worker.
 Build  [=================== ] 93% (11.0s) after chunk asset optimizationUnable to read file: /home/lmerza/projects/src/src/core/Util.js

ReferenceError: window is not defined
method: null
at: /home/lmerza/projects/src/src/core/Util.js:217:23

Source code:


This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.
```

**Comment by ljmerza** [comment]
Looks like it's because the prerendering is on by default. If I turn this off then it works.

**Comment by rschristian** [comment]
That is the "nice prerender build error" mentioned above. This issue was opened due to that being broken.

You usually can wrap the offending code in a [window check](https://github.com/preactjs/preact-cli#pre-rendering) (as the `setTimeout` probably isn't necessary for prerendering) or just use a `// @ts-ignore` comment. There's also this SO post that may work? https://stackoverflow.com/a/56239226/15388164
